version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    # Uncomment when need to run in dev profile with persistent DB
    # depends_on:
    #   - db

  # Example of a persistent service to run in dev profile
  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: invoice_db
  #   ports:
  #     - "5432:5432"
