version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev1
    # Uncomment when need to run in dev2 profile with persistent DB
    # depends_on:
    #   - db

  # Example of a persistent service to run in dev profile
#  db:
#    image: mysql:8.0
#    environment:
#      MYSQL_DATABASE: yourdatabase
#      MYSQL_USER: yourusername
#      MYSQL_PASSWORD: yourpassword
#      MYSQL_ROOT_PASSWORD: rootpassword
#    ports:
#      - "3306:3306"

#volumes:
#  db-data: